export const SIGNING_UP = "SIGNING_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const SIGNING_IN = "SIGNING_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

export const IS_USER_AUTHENTICATED = "IS_USER_AUTHENTICATED";

export const GETING_CURRENT_SESSION = "GETING_CURRENT_SESSION";
export const GETING_CURRENT_SESSION_ERROR = "GETING_CURRENT_SESSION_ERROR";
export const GETING_CURRENT_SESSION_SUCCESS = "GETING_CURRENT_SESSION_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";

export const GETTING_USER_FILES = "GETTING_USER_FILES";
export const GETTING_USER_FILES_SUCCESS = "GETTING_USER_FILES_SUCCESS";
export const GETTING_USER_FILES_ERROR = "GETTING_USER_FILES_ERROR";